### PR TITLE
Issue116: Document how to manage transaction propagation

### PR DESCRIPTION
**Pull request by mmusgrov**
#116 

This PR adds an example to the documentation of how to manage transaction propagation.

### CODE REVIEW

**Comment by Emily-Jiang** [comment]
I disagree that MP concurrency should contain any transaction test. As said yesterday, MP Concurrency should define a framework on how to opt in for context propagation not defining what should be propagated.

**Comment by njr-11** [comment]
> I disagree that MP concurrency should contain any transaction test.

This comment is out of place under this pull.  This pull does not deliver any tests.  It documents and example code snippet of using the MP Concurrency spec in conjunction with a JTA implementation that propagates context.  We have other examples snippets that illustrate other context types, such as propagation of the java:comp/env namespace so that you can look up a data source, so I cannot see why we would omit transaction context examples.  The fact that we gave an example of JNDI doesn't mean that all implementation must support JNDI, nor does including an example of transaction context propagation mean that all implementations must support JTA or transaction context propagation.  I could see prefacing these sort of examples with something along the lines of, "For implementations that support propagation of JTA transactions, the following guidelines and examples demonstrate possible common usage patterns, ..." but it would take away from the usability of the spec not to have good examples that users can refer to.

**Comment by mmusgrov** [comment]
I added a commit that points out that transaction propagation is optional.

**Comment by njr-11** [comment]
Cancelling this as discussed under 140.

**Pull request closed without merging**
